# Generated by Django 5.2.14 on 2026-05-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apodo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='color_cinturon',
            field=models.CharField(blank=True, choices=[('Blanco', 'Blanco'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Verde', 'Verde'), ('Azul', 'Azul'), ('Marrón', 'Marrón'), ('Negro', 'Negro')], max_length=50),
        ),
    ]
