# Generated by Django 5.2.14 on 2026-05-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0003_perfil_apodo_perfil_color_cinturon'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dan',
            field=models.CharField(blank=True, choices=[('Sin Dan', 'Sin Dan'), ('1° Dan', '1° Dan'), ('2° Dan', '2° Dan'), ('3° Dan', '3° Dan'), ('4° Dan', '4° Dan'), ('5° Dan', '5° Dan'), ('6° Dan', '6° Dan'), ('7° Dan', '7° Dan'), ('8° Dan', '8° Dan'), ('9° Dan', '9° Dan'), ('10° Dan', '10° Dan')], max_length=20),
        ),
    ]
