# Generated by Django 5.2.14 on 2026-05-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0004_perfil_dan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiadojo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='historias_dojo/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='color_cinturon',
            field=models.CharField(blank=True, choices=[('Blanco', 'Blanco'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Verde', 'Verde'), ('Morado', 'Morado'), ('Marrón', 'Marrón'), ('Negro', 'Negro')], max_length=50),
        ),
    ]
