# Generated by Django 5.2.14 on 2026-05-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0005_alter_historiadojo_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiadojo',
            name='mostrar_galeria',
            field=models.BooleanField(default=False),
        ),
    ]
