# Generated by Django 4.2.11 on 2026-05-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0006_historiadojo_mostrar_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatePactado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='combates/')),
                ('descripcion', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates', to='temple.evento')),
            ],
        ),
    ]
