# Generated by Django 5.2.14 on 2026-05-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0007_combatepactado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='aprobado_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='color_cinturon_pendiente',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
