# Generated by Django 5.2.14 on 2026-05-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0008_perfil_aprobado_por_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dan_pendiente',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
