# Generated by Django 5.2.14 on 2026-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0009_perfil_dan_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='derrotas_amateur',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='victorias_amateur',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
