# Generated by Django 5.2.14 on 2026-05-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0010_perfil_derrotas_amateur_perfil_victorias_amateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner_perfil',
            field=models.CharField(choices=[('fondo-pagina.png', 'Banner actual'), ('Banners1.png', 'Banner Dojo'), ('Banners2.png', 'Banner Fuego'), ('Banners3.png', 'Banner Zen'), ('Banners4.png', 'Banner Samurai')], default='fondo-pagina.png', max_length=100),
        ),
    ]
