# Generated by Django 5.2.14 on 2026-05-31 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0012_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='temple.evento'),
        ),
    ]
